import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import copy from "esbuild-copy-files-plugin";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const PATHS_TEST_INSTALL = process.env?.PATHS_TEST_INSTALL || "";
const PATH_TEST_INSTALL = PATHS_TEST_INSTALL.split(path.delimiter)
	.map((p) => p.trim())
	.filter((p) => p.length);
if (PATH_TEST_INSTALL) {
	console.log(`Built files will be copied to ${PATH_TEST_INSTALL}`);
} else {
	console.log(
		"Development build: You can install the plug-in to Obsidian for testing by exporting the PATHS_TEST_INSTALL environment variable with the paths to your vault plugins directories separated by your system path delimiter (':' on Unix, ';' on Windows).",
	);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [
		copy({
			source: [
				"./main.js",
				"./manifest.json",
				"./style.css",
				".hotreload",
			],
			target: PATH_TEST_INSTALL,
			copyWithFolder: true, // will copy "images" folder with all files inside
		}),
	],
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
